version: "3"
services:
  # ------- general ------ #
  redis:
    image: redis:7.2.4
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5
      start_period: 10s
    expose:
      - "${REDIS_PORT}"
  
  rabbitmq:
    image: rabbitmq:3.13.3-management
    container_name: rabbitmq   
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_pASSWORD}
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

  # ------- auth service ------ #
  auth_db:
    image: postgres:13
    container_name: auth_db
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
      - pgdbauth_all:/var/lib/postgresql@13/data/
    ports:
      - "${AUTH_DB_PORT}:${AUTH_DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${AUTH_DB_NAME} -U ${AUTH_DB_USER}"]
      interval: 5s
      timeout: 10s
      retries: 5

  auth_service:
    build:
      context: .
      dockerfile: ./auth/auth.Dockerfile
    command: sh -c "alembic upgrade head && python3 src/main.py"
    container_name: auth_service
    volumes:
      - ./auth/src/migrations:/app/src/migrations
    ports:
      - "8000:${AUTH_API_PORT}"
    depends_on:
      redis:
        condition: service_healthy
      auth_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./auth/compose.env

  # # ------- loyalty service ------ #
  loyalty_db:
    image: postgres:13
    container_name: loyalty_db
    environment:
      POSTGRES_DB: ${LOYALTY_DB_NAME}
      POSTGRES_USER: ${LOYALTY_DB_USER}
      POSTGRES_PASSWORD: ${LOYALTY_DB_PASSWORD}
    volumes:
      - pgdbloyalty_all:/var/lib/postgresql@13/data/
    ports:
      - "5433:${LOYALTY_DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${LOYALTY_DB_NAME} -U ${LOYALTY_DB_USER}"]
      interval: 5s
      timeout: 10s
      retries: 5


  loyalty_admin_service:
    container_name: loyalty_admin_service
    build:
      context: .
      dockerfile: ./admin/django.Dockerfile
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --no-input --clear && gunicorn config.wsgi:application --bind ${LOYALTY_ADMIN_HOST}:${LOYALTY_ADMIN_PORT}"
    ports:
      - "8080:${LOYALTY_ADMIN_PORT}"
    volumes:
      - static_volume_all:/app/static
    depends_on:
      loyalty_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./admin/compose.env

  loyalty_api_service:
    container_name: loyalty_api_service
    build:
      context: .
      dockerfile: ./loyalty/loyalty.Dockerfile
    ports:
      - "8081:${LOYALTY_ADMIN_PORT}"
    command: sh -c "python src/main.py"
    depends_on:
      loyalty_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./loyalty/compose.env

  loyalty_worker_reg:
    build:
      context: .
      dockerfile: ./worker/worker.Dockerfile
    container_name: loyalty_worker_reg
    command: sh -c "python3 main.py users.registration"
    depends_on:
      rabbitmq:
        condition: service_healthy
      loyalty_db:
        condition: service_healthy
    env_file:
      - ./worker/compose.env
  
  loyalty_worker_del:
    build:
      context: .
      dockerfile: ./worker/worker.Dockerfile
    container_name: loyalty_worker_del
    command: sh -c "python3 main.py users.delete"
    depends_on:
      rabbitmq:
        condition: service_healthy
      loyalty_db:
        condition: service_healthy
    env_file:
      - ./worker/compose.env

  cloudbeaver:
    image: dbeaver/cloudbeaver:24.0.5
    container_name: services-dbeaver
    ports:
      - '8978:8978'
    volumes: 
      - cloudbeaver:/opt/cloudbeaver/workspace 

volumes:
  pgdbauth_all:
  pgdbloyalty_all:
  static_volume_all:
  cloudbeaver:
