"""change users table

Revision ID: e00a5d5cfe7b
Revises: 2124ac7abb76
Create Date: 2024-07-20 21:06:22.931174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e00a5d5cfe7b'
down_revision: Union[str, None] = '2124ac7abb76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authentication', ['id'])
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_staff')
    op.drop_constraint(None, 'authentication', type_='unique')

    # ### end Alembic commands ###
